export const projectsData = [
  {
    id: 1,
    name: "Una Film Distribucija",
    description: "Web application for distributing movies and film news. Users can view movies, trailers, news and other content, while administrators manage content via a dashboard.",
    date: "Web App",
    demoLink: "https://unafilm.ba/",
    image: "/background/unafilm.png",
  },
  {
    id: 2,
    name: "Music Streaming Service",
    description: "Mobile music streaming app focused on a customizable user experience with innovative features like offline mode.",
    date: "Mobile App",
    demoLink: "https://github.com/Hamza9199/MusicStreamingService",
    image: "/background/work.png",
  },
  {
    id: 3,
    name: "Cats Defenders",
    description: "Space‑Invaders style game in C# (Windows Forms). Control a cat defending its territory from enemy attacks and survive as long as possible.",
    date: "Game",
    demoLink: "https://github.com/Hamza9199/Cats-Defenders",
    image: "/background/work.png",
  },
  {
    id: 4,
    name: "ForgeAI",
    description: "Advanced music production technology enabling intuitive music generation using text prompts and AI models for high quality and flexibility.",
    date: "Plugin, Web App",
    demoLink: "https://github.com/SafetImamovic/ForgeAI",
    image: "/background/work.png",
  },
  {
    id: 5,
    name: "TrailerFlix",
    description: "Web app for viewing and organizing movie trailers, built as part of a Web Design course. Includes search, viewing, auth and a personalized dashboard.",
    date: "Web App",
    demoLink: "https://github.com/Hamza9199/TrailerFlix",
    image: "/background/work.png",
  },
  {
    id: 6,
    name: "Audio System",
    description: "Desktop music player built in C++ with OOP focus. Browse, listen to and manage locally stored music like classic Windows players.",
    date: "Desktop App",
    demoLink: "https://github.com/SafetImamovic/AudioSystem",
    image: "/background/work.png",
  },
  {
    id: 7,
    name: "RedBullShop",
    description: "E‑commerce web app for browsing products, cart, orders, reviews, and user profile management (frontend + backend).",
    date: "Web App",
    demoLink: "https://github.com/Hamza9199/RedBullShop",
    image: "/background/work.png",
  },
  {
    id: 8,
    name: "Sistem Prijave za Posao",
    description: "Full‑stack app for managing users, jobs and reviews. Backend in Spring Boot, frontend in React; includes setup and run instructions.",
    date: "Web App",
    demoLink: "https://github.com/Hamza9199/WEBZadace",
    image: "/background/work.png",
  },
  {
    id: 9,
    name: "End‑to‑End (E2E) testiranje u React aplikacijama",
    description: "Focus on E2E testing in React apps using Cypress to ensure functionality and user experience in modern web development.",
    date: "Web App Testing",
    demoLink: "https://github.com/Hamza9199/E2ETestZadaca",
  image: "/background/work.png",
  },
  {
    id: 10,
    name: "Embedded Smart Car System",
    description: "Vehicle with dual MCU, sensor fusion, environmental monitoring and IR remote control.",
    date: "MCU",
    demoLink: "https://github.com/SafetImamovic/US-Auto",
  image: "/background/work.png",
  },
  {
    id: 11,
    name: "DecibelOld",
    description: "Modern music platform for listening, playlists, following artists, and interactions (comments/likes) with a simple user experience.",
    date: "Web App",
    demoLink: "https://github.com/Hamza9199/DecibelOld",
    image: "/background/work.png",
  },
];

export const BtnList = [
  { label: "Home", i18nKey: "nav.home", link: "/", icon: "home", newTab: false },
  { label: "About", i18nKey: "nav.about", link: "/about", icon: "about", newTab: false },
  { label: "Projects", i18nKey: "nav.projects", link: "/projects", icon: "projects", newTab: false },
  { label: "Contact", i18nKey: "nav.contact", link: "/contact", icon: "contact", newTab: false },
  { label: "Github", i18nKey: "nav.github", link: "https://github.com/Hamza9199", icon: "github", newTab: true },
  { label: "LinkedIn", i18nKey: "nav.linkedin", link: "https://www.linkedin.com/in/hamza-gacic-dev/", icon: "linkedin", newTab: true },
  { label: "Instagram", i18nKey: "nav.instagram", link: "https://www.instagram.com/hamza.1_____", icon: "instagram", newTab: true },
  { label: "Resume", i18nKey: "nav.resume", link: "/resume.pdf", icon: "resume", newTab: true },
];


